# Generated by Django 5.1.5 on 2025-01-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category_remove_post_category_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Leadership', 'Leadership'), ('Motivation', 'Motivation'), ('Inspiration', 'Inspiration'), ('Technology', 'Technology'), ('Frameworks', 'Frameworks'), ('Design', 'Design'), ('Research', 'Research'), ('Software Development', 'Software Development')], max_length=200, unique=True),
        ),
    ]
